{{- if eq .Values.scheduler.mode "plugin" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-hiro-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hiro-scheduler
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.scheduler.plugin.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
