apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hiro-scheduler
  labels:
    app.kubernetes.io/name: hiro-scheduler
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hiro-scheduler
subjects:
  - kind: ServiceAccount
    name: hiro-scheduler
    namespace: system
