apiVersion: orchestration.hiro.io/v1alpha1
kind: OrchestrationProfile
metadata:
  labels:
    app.kubernetes.io/name: hiro-adaptive-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: orchestrationprofile-sample
spec:
  # TODO(user): Add fields here
  applicationRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
    namespace: default

  placement:
    strategy: EnergyAware
    awareness:
      cpu: false
      memory: false
      gpu: false
      energy: true

  rebalancing:
    enabled: true
    cooldownSeconds: 300
    triggerConditions:
      - "EnergyThreshold"
