{{- if .Values.webhook.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-mutating-webhook-configuration
  {{- if .Values.webhook.certManager.enable }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-serving-cert
  {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Release.Name }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate--v1-pod
    failurePolicy: Ignore
    name: mpod-v1.kb.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            {{- toYaml .Values.webhook.excludeNamespaces | nindent 12 }}
{{- end }}
